Display draft cards
WildCodeSchool/2103-lille-js-p2-g1-heroes pull request #1
Opened 2021-04-21 08:31 UTC by ThomasSupervil

Add the display of the 20 random cards from the API

2021-04-21 08:37 UTC, CaroD59 submitted a review, later dismissed

2021-04-21 15:05 UTC, CaroD59 submitted a review, later dismissed
Ok ! :)

2021-04-21 17:38 UTC, LoicBrassart approved these changes, later dismissed
No real Evil, good job!

2021-04-21 17:38 UTC, LoicBrassart commented on src/components/Draft/Cards.jsx
> +        .get(`https://superheroapi.com/api.php/4118415658211107/${randomID}`)
It would be better to store the API key in a `.env` file
(Not seen yet)

2021-04-22 10:17 UTC, CaroD59 approved these changes, later dismissed
Ok for me !

2021-04-22 11:35 UTC, CaroD59 submitted a review, later dismissed
Ok for me !

2021-04-22 13:46 UTC, LoicBrassart requested changes
Some file cleanup to do

2021-04-22 13:46 UTC, LoicBrassart commented on public/reset.css
> +/* http://meyerweb.com/eric/tools/css/reset/
This file has nothing to do here ? 
It should be in `src` (and there **is** another copy in `src`!)

2021-04-22 13:46 UTC, LoicBrassart commented on src/style.css
> +
What's this ? An empty file ? Delete it

2021-04-22 13:58 UTC, Sofiaboud commented on src/style.css
> +
done

2021-04-22 14:05 UTC, LoicBrassart commented
- SM validation before assigning me (frustrating, uh ? :p )
- Resolve conflicts before assigning me

2021-04-22 14:17 UTC, CaroD59 approved these changes
Ok for me :)

2021-04-23 06:25 UTC, LoicBrassart approved these changes
No more Evil

2021-04-23 09:35 UTC, merged